hosts: localhost
tasks:
  - name: Pull maven jdk17 image
    docker_image:
      name: maven
      tag: 3.8.3-openjdk-17
      source: pull

  - name: Stop and remove existing container if present
    docker_container:
      name: maven_container
      state: absent

  - name: Create docker container & build app
    docker_container:
      name: maven_container
      image: maven:3.8.3-openjdk-17
      state: started
      volumes:
        - ./spring-boot:/app
      working_dir: /app
      command: mvn clean install
