hosts: localhost
tasks:
  - name: Stop and remove existing app container if present
    docker_container:
      name: app_container
      state: absent

  - name: Deploy app
    docker_container:
      name: app_container
      image: maven:3.8.3-openjdk-17
      state: started
      volumes:
        - ./spring-boot/target:/app
      working_dir: /app
      command: ./mvnw spring-boot:run
