pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                withGradle() {
                    sh './gradlew clean build'
                }
            }
        }

//         stage('Test') {
//             steps {
//                 script {
//                     sh './gradlew test'
//                 }
//             }
//         }
//
//         stage('Allure Report') {
//             steps {
//                 allure([
//                     results: [[path: 'build/allure-results']]
//                 ])
//             }
//         }
//
//         stage('SonarQube Analysis') {
//             steps {
//                 withSonarQubeEnv('SonarQube') {
//                     sh './gradlew sonarqube'
//                 }
//             }
//         }
//
//         stage('Build Container') {
//             steps {
//                 script {
//                     sh 'docker build -t my-app:${env.BUILD_NUMBER} .'
//                 }
//             }
//         }
//     }
//
//     post {
//         always {
//             junit 'build/test-results/**/*.xml'
//         }
    }
}
